  /galaxy/server/tools/interactive/biocworkshop_eurobioc2025isee.xml:
    useSecret: false
    applyToJob: true
    applyToSetupJob: true
    applyToWeb: true
    applyToWorkflow: true
    applyToNginx: true
    tpl: false
    content: |
      <tool id="interactivetool_biocworkshop_eurobioc2025isee" tool_type="interactive" name="iSEE Workshop" version="0.1">
          <description>Learn how to use the iSEE package, in a compact 2-hours workshop!</description>
          <requirements>
              <container type="docker">ghcr.io/isee/iseeworkshopeurobioc2025:latest</container>
          </requirements>
          <entry_points>
              <entry_point name="eurobioc2025isee" requires_domain="True">
                  <port>8787</port>
              </entry_point>
          </entry_points>
          <environment_variables>
              <environment_variable name="DISABLE_AUTH">true</environment_variable>
              <environment_variable name="HISTORY_ID">$__history_id__</environment_variable>
              <environment_variable name="REMOTE_HOST">$__galaxy_url__</environment_variable>
              <environment_variable name="GALAXY_URL">$__galaxy_url__</environment_variable>
              <environment_variable name="API_KEY" inject="api_key" />
          </environment_variables>
          <command detect_errors="aggressive">export TEMP=/tmp TMP=/tmp TMPDIR=/tmp TEMPDIR=/tmp; if [ -f '/home/rstudio/iSEEWorkshopEuroBioc2025/vignettes/Introduction_to_iSEEWorkshopEuroBioc2025.Rmd' ]; then echo '/home/rstudio/iSEEWorkshopEuroBioc2025/vignettes/Introduction_to_iSEEWorkshopEuroBioc2025.Rmd' > /tmp/startfile; else echo '/home/rstudio/vignettes/Introduction_to_iSEEWorkshopEuroBioc2025.Rmd' > /tmp/startfile; fi ; echo "{ 'visual_markdown_editing_is_default': true }" > /etc/rstudio/rstudio-prefs.json ; echo "setwd('/home/rstudio'); setHook('rstudio.sessionInit', function(newSession) { if (newSession) rstudioapi::filesPaneNavigate('\$(dirname \$(cat /tmp/startfile))'); rstudioapi::navigateToFile('\$(cat /tmp/startfile)') }, action = 'append')" > /home/rstudio/.Rprofile; export TEMP=/tmp TMP=/tmp TMPDIR=/tmp TEMPDIR=/tmp; chown -R rstudio /home/rstudio/*; rm /tmp/startfile; chown -R rstudio /home/rstudio/.*; /init</command>
          <inputs>
          </inputs>
          <outputs>
          </outputs>
          <tests>
          </tests>
          <help>This is an autogenerated Bioconductor workshop wrapper. See the source of this workshop or report issues at https://github.com/iSEE/iSEEWorkshopEuroBioc2025.</help>
      </tool>
