  /galaxy/server/tools/interactive/biocworkshop_oscaismb2023.xml:
    useSecret: false
    applyToJob: true
    applyToSetupJob: true
    applyToWeb: true
    applyToWorkflow: true
    applyToNginx: true
    tpl: false
    content: |
      <tool id="interactivetool_biocworkshop_oscaismb2023" tool_type="interactive" name="Orchestrating Large-Scale Single-Cell Analysis with Bioconductor" version="0.1">
          <description>Using Bioconductor tools for single-cell RNA-seq analysis</description>
          <requirements>
              <container type="docker">ghcr.io/bioconductor/ismb.osca:latest</container>
          </requirements>
          <entry_points>
              <entry_point name="oscaismb2023" requires_domain="True">
                  <port>8787</port>
              </entry_point>
          </entry_points>
          <environment_variables>
              <environment_variable name="DISABLE_AUTH">true</environment_variable>
              <environment_variable name="HISTORY_ID">$__history_id__</environment_variable>
              <environment_variable name="REMOTE_HOST">$__galaxy_url__</environment_variable>
              <environment_variable name="GALAXY_URL">$__galaxy_url__</environment_variable>
              <environment_variable name="API_KEY" inject="api_key" />
          </environment_variables>
          <command detect_errors="aggressive">if [ -f '/home/rstudio/ISMB.OSCA/README.md' ]; then echo '/home/rstudio/ISMB.OSCA/README.md' > /tmp/startfile; else echo '/home/rstudio/README.md' > /tmp/startfile; fi ; echo "{ 'visual_markdown_editing_is_default': true }" > /etc/rstudio/rstudio-prefs.json ; echo "setwd('/home/rstudio'); setHook('rstudio.sessionInit', function(newSession) { if (newSession) rstudioapi::filesPaneNavigate('\$(dirname \$(cat /tmp/startfile))'); rstudioapi::navigateToFile('\$(cat /tmp/startfile)') }, action = 'append')" > /home/rstudio/.Rprofile; chown -R rstudio /home/rstudio/*; rm /tmp/startfile; chown -R rstudio /home/rstudio/.*; /init</command>
          <inputs>
          </inputs>
          <outputs>
          </outputs>
          <tests>
          </tests>
          <help>This is an autogenerated Bioconductor workshop wrapper. See the source of this workshop or report issues at github.com/Bioconductor/ISMB.OSCA.</help>
      </tool>
