  /galaxy/server/tools/interactive/biocworkshop_ranseq123317.xml:
    useSecret: false
    applyToJob: true
    applyToSetupJob: true
    applyToWeb: true
    applyToWorkflow: true
    applyToNginx: true
    tpl: false
    content: |
      <tool id="interactivetool_biocworkshop_ranseq123317" tool_type="interactive" name="RNA-seq analysis" version="0.1">
          <description>as easy as 1-2-3 with limma, Glimma and edgeR</description>
          <requirements>
              <container type="docker">ghcr.io/bioconductor/workshop-contributions:devel-59fbac27</container>
          </requirements>
          <entry_points>
              <entry_point name="ranseq123317" requires_domain="True">
                  <port>8787</port>
              </entry_point>
          </entry_points>
          <environment_variables>
              <environment_variable name="DISABLE_AUTH">true</environment_variable>
              <environment_variable name="HISTORY_ID">$__history_id__</environment_variable>
              <environment_variable name="REMOTE_HOST">$__galaxy_url__</environment_variable>
              <environment_variable name="GALAXY_URL">$__galaxy_url__</environment_variable>
              <environment_variable name="API_KEY" inject="api_key" />
          </environment_variables>
          <command detect_errors="aggressive">if [ -f '/home/rstudio/RNAseq123/vignettes/limmaWorkflow.Rmd' ]; then echo '/home/rstudio/RNAseq123/vignettes/limmaWorkflow.Rmd' > /tmp/startfile; else echo '/home/rstudio/vignettes/limmaWorkflow.Rmd' > /tmp/startfile; fi ; echo "{ 'visual_markdown_editing_is_default': true }" > /etc/rstudio/rstudio-prefs.json ; echo "setwd('/home/rstudio'); setHook('rstudio.sessionInit', function(newSession) { if (newSession) rstudioapi::filesPaneNavigate('\$(dirname \$(cat /tmp/startfile))'); rstudioapi::navigateToFile('\$(cat /tmp/startfile)') }, action = 'append')" > /home/rstudio/.Rprofile; chown -R rstudio /home/rstudio/*; rm /tmp/startfile; chown -R rstudio /home/rstudio/.*; /init</command>
          <inputs>
          </inputs>
          <outputs>
          </outputs>
          <tests>
          </tests>
          <help>
              This is an autogenerated Bioconductor workshop wrapper.
              See this workshop website at http://bioconductor.org/packages/release/workflows/vignettes/RNAseq123/inst/doc/limmaWorkflow.html.
              For the source of this workshop see https://git.bioconductor.org/packages/RNAseq123.
          </help>
      </tool>
