  /galaxy/server/tools/interactive/biocworkshop_bioc2024tidyworkshop.xml:
    useSecret: false
    applyToJob: true
    applyToSetupJob: true
    applyToWeb: true
    applyToWorkflow: true
    applyToNginx: true
    tpl: false
    content: |
      <tool id="interactivetool_biocworkshop_bioc2024tidyworkshop" tool_type="interactive" name="Applying tidy principles to investigating chromatin composition and architecture" version="0.1">
          <description>This workshop aims to demonstrate how to use methodology to investigate genomic data, including genomic features, genomic interactions and genomic coverage.</description>
          <requirements>
              <container type="docker">ghcr.io/js2264/bioc2024tidyworkshop:latest</container>
          </requirements>
          <entry_points>
              <entry_point name="bioc2024tidyworkshop" requires_domain="True">
                  <port>8787</port>
              </entry_point>
          </entry_points>
          <environment_variables>
              <environment_variable name="DISABLE_AUTH">true</environment_variable>
              <environment_variable name="HISTORY_ID">$__history_id__</environment_variable>
              <environment_variable name="REMOTE_HOST">$__galaxy_url__</environment_variable>
              <environment_variable name="GALAXY_URL">$__galaxy_url__</environment_variable>
              <environment_variable name="API_KEY" inject="api_key" />
          </environment_variables>
          <command detect_errors="aggressive">export TEMP=/tmp TMP=/tmp TMPDIR=/tmp TEMPDIR=/tmp; if [ -f '/home/rstudio/Bioc2024tidyworkshop/vignettes/workshop.Rmd' ]; then echo '/home/rstudio/Bioc2024tidyworkshop/vignettes/workshop.Rmd' > /tmp/startfile; else echo '/home/rstudio/vignettes/workshop.Rmd' > /tmp/startfile; fi ; echo "{ 'visual_markdown_editing_is_default': true }" > /etc/rstudio/rstudio-prefs.json ; echo "setwd('/home/rstudio'); setHook('rstudio.sessionInit', function(newSession) { if (newSession) rstudioapi::filesPaneNavigate('\$(dirname \$(cat /tmp/startfile))'); rstudioapi::navigateToFile('\$(cat /tmp/startfile)') }, action = 'append')" > /home/rstudio/.Rprofile; export TEMP=/tmp TMP=/tmp TMPDIR=/tmp TEMPDIR=/tmp; chown -R rstudio /home/rstudio/*; rm /tmp/startfile; chown -R rstudio /home/rstudio/.*; /init</command>
          <inputs>
          </inputs>
          <outputs>
          </outputs>
          <tests>
          </tests>
          <help>This is an autogenerated Bioconductor workshop wrapper. See the source of this workshop or report issues at https://github.com/js2264/Bioc2024tidyworkshop.</help>
      </tool>
