  /galaxy/server/tools/interactive/biocworkshop_iseeworkshop2020.xml:
    useSecret: false
    applyToJob: true
    applyToSetupJob: true
    applyToWeb: true
    applyToWorkflow: true
    applyToNginx: true
    tpl: false
    content: |
      <tool id="interactivetool_biocworkshop_iseeworkshop2020" tool_type="interactive" name="iSEE" version="0.1">
          <description>Interactive visualization of SummarizedExperiment objects</description>
          <requirements>
              <container type="docker">ghcr.io/isee/iseeworkshop2020/iseeworkshop2020:latest</container>
          </requirements>
          <entry_points>
              <entry_point name="iseeworkshop2020" requires_domain="True">
                  <port>8787</port>
              </entry_point>
          </entry_points>
          <environment_variables>
              <environment_variable name="DISABLE_AUTH">true</environment_variable>
              <environment_variable name="HISTORY_ID">$__history_id__</environment_variable>
              <environment_variable name="REMOTE_HOST">$__galaxy_url__</environment_variable>
              <environment_variable name="GALAXY_URL">$__galaxy_url__</environment_variable>
              <environment_variable name="API_KEY" inject="api_key" />
          </environment_variables>
          <command detect_errors="aggressive">if [ -f iSEEWorkshop2020/vignettes/iSEE-lab.Rmd ]; then echo iSEEWorkshop2020/vignettes/iSEE-lab.Rmd > startpathfile; else echo vignettes/iSEE-lab.Rmd > startpathfile; fi ; echo "{ 'visual_markdown_editing_is_default': true }" > /etc/rstudio/rstudio-prefs.json ; echo "setwd('/home/rstudio'); setHook('rstudio.sessionInit', function(newSession) { if (newSession) rstudioapi::filesPaneNavigate(getwd()); rstudioapi::navigateToFile('/home/rstudio/$(cat startpathfile)') }, action = 'append')" > /home/rstudio/.Rprofile; chown -R rstudio /home/rstudio/*; chown -R rstudio /home/rstudio/.*; /init</command>
          <inputs>
          </inputs>
          <outputs>
          </outputs>
          <tests>
          </tests>
          <help>This is an autogenerated Bioconductor workshop wrapper. See the source of this workshop or report issues at https://github.com/iSEE/iSEEWorkshop2020.</help>
      </tool>
