  /galaxy/server/tools/interactive/biocworkshop_singscoreamlmutations317.xml:
    useSecret: false
    applyToJob: true
    applyToSetupJob: true
    applyToWeb: true
    applyToWorkflow: true
    applyToNginx: true
    tpl: false
    content: |
      <tool id="interactivetool_biocworkshop_singscoreamlmutations317" tool_type="interactive" name="Using singscore" version="0.1">
          <description>to predict mutations in AML from transcriptomic signatures</description>
          <requirements>
              <container type="docker">ghcr.io/bioconductor/workshop-contributions:devel-c0fab7ee</container>
          </requirements>
          <entry_points>
              <entry_point name="singscoreamlmutations317" requires_domain="True">
                  <port>8787</port>
              </entry_point>
          </entry_points>
          <environment_variables>
              <environment_variable name="DISABLE_AUTH">true</environment_variable>
              <environment_variable name="HISTORY_ID">$__history_id__</environment_variable>
              <environment_variable name="REMOTE_HOST">$__galaxy_url__</environment_variable>
              <environment_variable name="GALAXY_URL">$__galaxy_url__</environment_variable>
              <environment_variable name="API_KEY" inject="api_key" />
          </environment_variables>
          <command detect_errors="aggressive">if [ -f '/home/rstudio/SingscoreAMLMutations/vignettes/workflow_transcriptional_mut_sig.Rmd' ]; then echo '/home/rstudio/SingscoreAMLMutations/vignettes/workflow_transcriptional_mut_sig.Rmd' > /tmp/startfile; else echo '/home/rstudio/vignettes/workflow_transcriptional_mut_sig.Rmd' > /tmp/startfile; fi ; echo "{ 'visual_markdown_editing_is_default': true }" > /etc/rstudio/rstudio-prefs.json ; echo "setwd('/home/rstudio'); setHook('rstudio.sessionInit', function(newSession) { if (newSession) rstudioapi::filesPaneNavigate('\$(dirname \$(cat /tmp/startfile))'); rstudioapi::navigateToFile('\$(cat /tmp/startfile)') }, action = 'append')" > /home/rstudio/.Rprofile; chown -R rstudio /home/rstudio/*; rm /tmp/startfile; chown -R rstudio /home/rstudio/.*; /init</command>
          <inputs>
          </inputs>
          <outputs>
          </outputs>
          <tests>
          </tests>
          <help>This is an autogenerated Bioconductor workshop wrapper. See the source of this workshop or report issues at https://git.bioconductor.org/packages/SingscoreAMLMutations.</help>
      </tool>
