name: Request workflow
on:
  repository_dispatch:
    types: [request-command]
jobs:
  generatevalues:
    name: Generate values
    runs-on: ubuntu-latest
    env:
      ISSUE_NUM: ${{ github.event.client_payload.github.payload.issue.number }}
    steps:
      - uses: actions/checkout@v3

      - name: Set defaults for all inputs
        id: defs
        run: |
          SRCURL=${{ github.event.client_payload.slash_command.args.named.source || '' }}
          if [ -z "$SRCURL" ]; then
            SRCURL="https://github.com/${{github.repository}}/issues/$ISSUE_NUM"
          fi
          echo source=$SRCURL >> $GITHUB_OUTPUT
          echo id=${{ github.event.client_payload.slash_command.args.named.id || 'error' }} >> $GITHUB_OUTPUT
          echo title=${{ github.event.client_payload.slash_command.args.named.title || 'No title' }} >> $GITHUB_OUTPUT
          echo description=${{ github.event.client_payload.slash_command.args.named.description || 'No description' }} >> $GITHUB_OUTPUT
          echo docker=${{ github.event.client_payload.slash_command.args.named.docker || 'ghcr.io/bioconductor/bioconductor:3.16' }} >> $GITHUB_OUTPUT
          echo port=${{ github.event.client_payload.slash_command.args.named.port || '8787' }} >> $GITHUB_OUTPUT
          echo command=${{ github.event.client_payload.slash_command.args.named.command || '/init' }} >> $GITHUB_OUTPUT
        
      - name: Test initial request
        id: reqtest
        run: bash .github/scripts/request.sh '${{steps.defs.outputs.id}}' '${{steps.defs.outputs.title}}' '${{steps.defs.outputs.description}}' '${{steps.defs.outputs.source}}' '${{steps.defs.outputs.docker}}' '${{steps.defs.outputs.port}}' '${{steps.defs.outputs.command}}'
        continue-on-error: true

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            _AUTO-GENERATED RESPONSE_
            Your request has been received and has passed initial screening. :sparkles:
            
            Below are the detected values:

            ```
            source='${{steps.defs.outputs.id}}'
            title='${{steps.defs.outputs.title}}'
            description='${{steps.defs.outputs.description}}'
            source='${{steps.defs.outputs.source}}'
            docker='${{steps.defs.outputs.docker}}'
            port='${{steps.defs.outputs.port}}'
            command='${{steps.defs.outputs.command}}'
            ```

            If these are as expected, no further action is needed at this time. Please wait for an admin's response.
            If any changes are needed, please re-run the /request action with desired values.
        if: steps.reqtest.outcome=='success'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            _AUTO-GENERATED RESPONSE_
            Your request has been received but is currently failinginitial screening.
            Please retry your request ensuring all parameters are passed in correctly. Eg:
            ```
            /request id="myuniqueid2023" title="Short title for my workshop" description="A description for my workshop. Multiple sentences in the same line." docker="ghcr.io/bioconductor/bioconductor:3.16" port="8787" command="/init"
            ```
            Note that port and command can be ignored if your image is based on the Bioconductor RStudio image
        if: steps.reqtest.outcome=='failure'


