name: Reset all cached images
on:
  workflow_dispatch:

jobs:
  deletepods:
    name: Reset DaemonSet pods
    runs-on: ubuntu-latest
    steps:
      - name: save kubeconfig
        shell: bash
        run: mkdir -p ~/.kube && echo "${{ secrets.TEST_KUBECONFIG }}" > ~/.kube/config
      - name: Install Kubectl
        run: curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl && kubectl version
      - name: Delete cache pods
        run: |
          CACHEPODS=$(kubectl get -o name pods -n cache-gxy)
          kubectl delete --wait -n cache-gxy $CACHEPODS
